import { useSelector } from "react-redux";
import {
  reduecFromCart,
  selectUserInfo,
} from "../../src/store/slices/clientSlice";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import imageLoader from "../../src/imageLoader";
import { imageAddress } from "..";
import { GoTrashcan } from "react-icons/go";
import { IoMdRemoveCircle } from "react-icons/io";
import { AddToCartType, Cart } from "../../src/types/types";
import { useAppDispatch } from "../../src/store/hooks";
import Shipping from "../../components/shipping/shipping";
import { useEffect, useState } from "react";
export default function CartPage() {
  const userInfo = useSelector(selectUserInfo);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="select-none flex flex-wrap h-fit font-Vazir-Bold justify-center items-start w-full ">
        <h1 className="flex text-center h-fit justify-center w-full font-Vazir-Medium text-2xl text-blackout-red">
          مشخصات
        </h1>
        {userInfo?.firstname !== undefined ? (
          <>
            <div className="flex justify-center w-full max-w-[800px] flex-wrap">
              <div className="flex w-full max-w-[800px] flex-wrap border mt-4 rounded-md text-gray-600 text-xs">
                <ul className="flex items-center h-fit w-full">
                  <li className="flex w-[110px]  mx-2 p-2">نام :</li>
                  <li className="flex  mx-2 p-2">{userInfo?.firstname}</li>
                </ul>
                <ul className="flex items-center h-fit  w-full">
                  <li className="flex  w-[110px] mx-2 p-2">نام خانوادگی:</li>
                  <li className="flex  mx-2 p-2">{userInfo?.lastname}</li>
                </ul>
              </div>
              <div className="flex w-full flex-wrap mt-4 text-gray-600 text-xs">
                <Shipping />
              </div>
              <h1 className="mt-20 flex text-center h-fit justify-center w-full font-Vazir-Medium text-2xl text-blackout-red">
                سبد خرید
              </h1>
              <div className="flex w-full justify-center">
                <CartContainer></CartContainer>
              </div>
            </div>
          </>
        ) : (
          <>
            <div className="flex justify-center text-3xl font-Vazir-Bold text-gray-600">
              سبد شما خالی میباشد
            </div>
          </>
        )}
        <div className="StickyContainer mt-4 w-fit max-w-[300px]">
          <ReportContainer cart={userInfo?.cart} />
        </div>
      </div>
    </>
  );
}

function ReportContainer({ cart }: { cart: Cart[] | undefined }) {
  const [cRep, setCrep] = useState<{
    total: number;
    benefit: number;
    qty: number;
  }>({
    total: 0,
    benefit: 0,
    qty: 0,
  });

  function calcSum() {
    var cartReport: { total: number; benefit: number; qty: number } = {
      total: 0,
      benefit: 0,
      qty: 0,
    };
    var TrrpPrice: number = 0;
    var TSellingPrice: number = 0;
    var TotalNumber: number = 0;
    cart?.map((item) => {
      TrrpPrice += item.variant.price.rrp_price * (item.quantity ?? 0);
      TSellingPrice += item.variant.price.selling_price * (item.quantity ?? 0);
      TotalNumber += item.quantity ?? 0;
    });
    cartReport.total = TSellingPrice;
    cartReport.benefit = Math.abs(TrrpPrice - TSellingPrice);
    cartReport.qty = TotalNumber;
    setCrep(cartReport);
  }

  useEffect(() => {
    calcSum();
  }, [cart]);

  const value: number = 115574;
  return (
    <>
      {cart !== undefined ? (
        <div className="md:flex flex w-full md:w-fit mx-2 rounded-md border shadow-lg">
          <ul className="flex flex-wrap w-fit justify-start m-4 font-Vazir-Medium">
            <li className="flex my-2 w-full">
              مبلغ کل :{" "}
              <span className="flex mx-2">
                {(cRep.total / 10).toLocaleString()}
              </span>{" "}
              تومان
            </li>
            <li className="flex my-2 w-full">
              سود شما از خرید :{" "}
              <span className="flex mx-2">
                {(cRep.benefit / 10).toLocaleString()}
              </span>{" "}
              تومان
            </li>
            <li className="flex my-2 w-full">
              هزینه ارسال و بسته بندی : <span className="flex mx-2">{0}</span>{" "}
              تومان
            </li>
            <li className="flex w-full border-b my-2"></li>
            <li className="flex my-2 w-full">
              قابل پرداخت :{" "}
              <span className="flex mx-2">
                {(cRep.total / 10).toLocaleString()}
              </span>{" "}
              تومان
            </li>
            <li className="flex my-2 justify-center w-full">
              <button className="bg-blackout-red w-fit rounded-md font-Vazir-Bold text-white p-4">
                ادامه و بازبینی سفارش
              </button>
            </li>
          </ul>
        </div>
      ) : (
        <></>
      )}
    </>
  );
}

function CartContainer() {
  const userInfo = useSelector(selectUserInfo);
  const dispatch = useAppDispatch();

  function handleReduceFromCart(productId: string, variantId: string) {
    if (
      userInfo._id !== undefined &&
      productId !== undefined &&
      userInfo.accessToken !== undefined
    ) {
      const reduce: AddToCartType = {
        accessToken: userInfo.accessToken,
        userId: userInfo._id,
        productId: productId,
        variantId: variantId,
      };
      dispatch(reduecFromCart(reduce));
    } else {
      console.log("please sign in first");
    }
  }

  return (
    <div className="flex text-sm md:text-lg flex-wrap w-full justify-center rounded-lg max-w-[400px] md:max-w-[800px]">
      {userInfo?.cart !== undefined ? (
        userInfo?.cart.map((cartItem, index) => (
          <>
            <CartItem
              key={index}
              cartItem={cartItem}
              handleReduceFromCart={handleReduceFromCart}
            />
          </>
        ))
      ) : (
        <></>
      )}
    </div>
  );
}

function CartItem({
  cartItem,
  handleReduceFromCart,
}: {
  cartItem: Cart;
  handleReduceFromCart: Function;
}) {
  return (
    <div className="flex w-full items-center rounded-md border shadow-lg h-[250px] my-4">
      <div className="flex justify-center w-1/6">
        <button
          onClick={() => {
            handleReduceFromCart(cartItem.productId, cartItem.variantId);
          }}
          className="text-sm "
        >
          <GoTrashcan color={"rgb(235,18,18)"} size={20} />
        </button>
      </div>
      <div className="flex w-auto">
        {" "}
        <Image
          className="flex md:w-[200px] md:h-[200px]  w-[100px] h-[100px] m-1 rounded-xl"
          loader={imageLoader}
          unoptimized
          quality="80"
          loading="eager"
          unselectable="on"
          draggable="false"
          placeholder="empty"
          src={imageAddress(
            cartItem?.ImageUrl,
            200,
            200,
            100,
            "webp",
            undefined
          )}
          alt={cartItem?.title_fa ?? "not-present"}
          width={100}
          height={100}
        />
      </div>
      <div className="flex w-4/6 h-full m-4 font-Vazir-Medium">
        <ul className="flex flex-wrap my-4 h-full w-4/6">
          <li className="my-2 flex w-full font-Vazir-Medium text-gray-500">
            {cartItem.title_fa}
          </li>
          <li className="my-2 flex w-full text-sm font-Vazir-Medium text-gray-500">
            {cartItem.variant.warranty}
          </li>
          {/* <li className="my-2 flex w-full">sss</li> */}
          <li className="my-2 flex w-full">
            <div className="input-color-container">
              {cartItem.variant.color.title}{" "}
              <input
                key="color"
                type={"color"}
                disabled
                className="input-color"
                value={cartItem.variant.color.hex_code}
              ></input>
            </div>
            <label className="mx-3 font-Vazir-Thin text-sm">
              {cartItem.variant.color.title}
            </label>
          </li>
        </ul>
        <div className="flex mx-2 flex-wrap justify-start w-2/6 h-full place-items-end">
          <div className="h-[200px]"></div>
          <div className="flex flex-wrap md:flex-nowrap h-fit w-full text-blackout-red my-4">
            <div className="flex h-fit w-fit mx-2 justify-end text-blackout-red">
              {cartItem?.Price !== undefined
                ? (cartItem?.Price / 10)?.toLocaleString()
                : "0"}{" "}
            </div>
            <div className="flex h-fit w-fit mx-2 justify-end text-cyan-400">
              تومان
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
